import type { Dataset, Model } from "./types"

export const mockDatasets: Dataset[] = [
  {
    id: "ds-001",
    name: "Customer Churn Analysis",
    description: "Telecom customer data for predicting churn behavior",
    source: "databricks",
    vertical: "marketing",
    complexity: "medium",
    rowCount: "medium",
    rows: 7043,
    columns: 21,
    lastUpdated: new Date("2024-01-18"),
    syncStatus: "synced",
    schema: [
      { name: "customer_id", type: "string", description: "Unique customer identifier" },
      { name: "tenure", type: "number", description: "Months with company" },
      { name: "monthly_charges", type: "number", description: "Monthly bill amount" },
      { name: "total_charges", type: "number", description: "Total amount charged" },
      { name: "churn", type: "boolean", description: "Whether customer churned" },
    ],
    sampleData: [
      { customer_id: "7590-VHVEG", tenure: 1, monthly_charges: 29.85, total_charges: 29.85, churn: false },
      { customer_id: "5575-GNVDE", tenure: 34, monthly_charges: 56.95, total_charges: 1889.5, churn: false },
    ],
  },
  {
    id: "ds-002",
    name: "Loan Default Prediction",
    description: "Banking data for credit risk assessment",
    source: "supabase",
    vertical: "finance",
    complexity: "advanced",
    rowCount: "large",
    rows: 32581,
    columns: 35,
    lastUpdated: new Date("2024-01-17"),
    syncStatus: "synced",
    schema: [
      { name: "loan_id", type: "string", description: "Unique loan identifier" },
      { name: "loan_amount", type: "number", description: "Principal amount" },
      { name: "interest_rate", type: "number", description: "Annual interest rate" },
      { name: "credit_score", type: "number", description: "Borrower credit score" },
      { name: "default", type: "boolean", description: "Whether loan defaulted" },
    ],
    sampleData: [
      { loan_id: "LN-001", loan_amount: 15000, interest_rate: 7.5, credit_score: 720, default: false },
      { loan_id: "LN-002", loan_amount: 8000, interest_rate: 12.3, credit_score: 645, default: true },
    ],
  },
  {
    id: "ds-003",
    name: "Patient Readmission",
    description: "Hospital records for predicting 30-day readmissions",
    source: "api",
    vertical: "healthcare",
    complexity: "advanced",
    rowCount: "large",
    rows: 25000,
    columns: 42,
    lastUpdated: new Date("2024-01-16"),
    syncStatus: "outdated",
    schema: [
      { name: "patient_id", type: "string", description: "Anonymized patient ID" },
      { name: "age", type: "number", description: "Patient age" },
      { name: "diagnosis_code", type: "string", description: "Primary diagnosis" },
      { name: "length_of_stay", type: "number", description: "Days in hospital" },
      { name: "readmitted", type: "boolean", description: "Readmitted within 30 days" },
    ],
    sampleData: [
      { patient_id: "P-8821", age: 67, diagnosis_code: "I50", length_of_stay: 5, readmitted: true },
      { patient_id: "P-9932", age: 45, diagnosis_code: "J18", length_of_stay: 3, readmitted: false },
    ],
  },
  {
    id: "ds-004",
    name: "E-commerce Transactions",
    description: "Online retail purchase data for demand forecasting",
    source: "google-drive",
    vertical: "e-commerce",
    complexity: "medium",
    rowCount: "medium",
    rows: 8950,
    columns: 18,
    lastUpdated: new Date("2024-01-15"),
    syncStatus: "synced",
    schema: [
      { name: "transaction_id", type: "string", description: "Transaction identifier" },
      { name: "product_category", type: "string", description: "Product category" },
      { name: "quantity", type: "number", description: "Items purchased" },
      { name: "revenue", type: "number", description: "Transaction revenue" },
      { name: "returned", type: "boolean", description: "Item returned" },
    ],
    sampleData: [
      { transaction_id: "TXN-4421", product_category: "Electronics", quantity: 2, revenue: 459.99, returned: false },
      { transaction_id: "TXN-4422", product_category: "Apparel", quantity: 1, revenue: 79.95, returned: true },
    ],
  },
  {
    id: "ds-005",
    name: "Employee Attrition",
    description: "HR analytics data for workforce planning",
    source: "databricks",
    vertical: "hr",
    complexity: "simple",
    rowCount: "small",
    rows: 1470,
    columns: 9,
    lastUpdated: new Date("2024-01-14"),
    syncStatus: "synced",
    schema: [
      { name: "employee_id", type: "string", description: "Employee identifier" },
      { name: "department", type: "string", description: "Department name" },
      { name: "years_at_company", type: "number", description: "Tenure in years" },
      { name: "satisfaction_score", type: "number", description: "Job satisfaction (1-5)" },
      { name: "attrition", type: "boolean", description: "Left the company" },
    ],
    sampleData: [
      { employee_id: "EMP-101", department: "Sales", years_at_company: 3, satisfaction_score: 4, attrition: false },
      {
        employee_id: "EMP-102",
        department: "Engineering",
        years_at_company: 1,
        satisfaction_score: 2,
        attrition: true,
      },
    ],
  },
  {
    id: "ds-006",
    name: "Supply Chain Delays",
    description: "Logistics data for delivery time prediction",
    source: "api",
    vertical: "operations",
    complexity: "medium",
    rowCount: "large",
    rows: 15420,
    columns: 24,
    lastUpdated: new Date("2024-01-13"),
    syncStatus: "pending",
    schema: [
      { name: "shipment_id", type: "string", description: "Shipment tracking ID" },
      { name: "origin", type: "string", description: "Origin warehouse" },
      { name: "destination", type: "string", description: "Delivery destination" },
      { name: "weight_kg", type: "number", description: "Package weight" },
      { name: "delayed", type: "boolean", description: "Shipment was delayed" },
    ],
    sampleData: [
      { shipment_id: "SHP-7721", origin: "NYC", destination: "LAX", weight_kg: 12.5, delayed: false },
      { shipment_id: "SHP-7722", origin: "CHI", destination: "MIA", weight_kg: 8.3, delayed: true },
    ],
  },
  {
    id: "ds-007",
    name: "Fraud Detection",
    description: "Financial transaction data for anomaly detection",
    source: "supabase",
    vertical: "finance",
    complexity: "advanced",
    rowCount: "large",
    rows: 284807,
    columns: 31,
    lastUpdated: new Date("2024-01-12"),
    syncStatus: "synced",
    schema: [
      { name: "transaction_id", type: "string", description: "Unique transaction ID" },
      { name: "amount", type: "number", description: "Transaction amount" },
      { name: "merchant_category", type: "string", description: "Merchant type" },
      { name: "time_delta", type: "number", description: "Time since last transaction" },
      { name: "is_fraud", type: "boolean", description: "Fraudulent transaction" },
    ],
    sampleData: [
      { transaction_id: "FT-001", amount: 149.62, merchant_category: "retail", time_delta: 0, is_fraud: false },
      { transaction_id: "FT-002", amount: 2.69, merchant_category: "online", time_delta: 0.5, is_fraud: false },
    ],
  },
  {
    id: "ds-008",
    name: "Marketing Campaign Response",
    description: "Direct marketing data for conversion prediction",
    source: "google-drive",
    vertical: "marketing",
    complexity: "simple",
    rowCount: "medium",
    rows: 4521,
    columns: 12,
    lastUpdated: new Date("2024-01-11"),
    syncStatus: "synced",
    schema: [
      { name: "contact_id", type: "string", description: "Contact identifier" },
      { name: "age", type: "number", description: "Customer age" },
      { name: "income", type: "number", description: "Annual income" },
      { name: "campaign_type", type: "string", description: "Campaign channel" },
      { name: "converted", type: "boolean", description: "Made a purchase" },
    ],
    sampleData: [
      { contact_id: "C-881", age: 35, income: 72000, campaign_type: "email", converted: true },
      { contact_id: "C-882", age: 28, income: 45000, campaign_type: "social", converted: false },
    ],
  },
]

export const mockModels: Model[] = [
  {
    id: "model-001",
    name: "Customer Intelligence",
    description: "AI model for customer behavior analysis and churn prediction",
    datasets: [
      {
        datasetId: "ds-001",
        datasetName: "Customer Churn Analysis",
        source: "databricks",
        rows: 7043,
        columns: 21,
        connectedAt: new Date("2024-01-15"),
        lastSynced: new Date("2024-01-18"),
        syncStatus: "synced",
      },
      {
        datasetId: "ds-008",
        datasetName: "Marketing Campaign Response",
        source: "google-drive",
        rows: 4521,
        columns: 12,
        connectedAt: new Date("2024-01-15"),
        lastSynced: new Date("2024-01-17"),
        syncStatus: "synced",
      },
    ],
    syncMode: "real-time",
    baseModel: "schema-v0",
    accuracy: 0.923,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-18"),
    status: "completed",
    modelId: "mdl_cust_intl_7x9k2",
    apiRequests: 12847,
    tokensUsed: 2456890,
    trainingMetricsHistory: [
      { epoch: 1, loss: 0.82, accuracy: 0.54 },
      { epoch: 5, loss: 0.58, accuracy: 0.71 },
      { epoch: 10, loss: 0.34, accuracy: 0.82 },
      { epoch: 15, loss: 0.21, accuracy: 0.89 },
      { epoch: 20, loss: 0.14, accuracy: 0.92 },
    ],
    endpoints: [
      {
        id: "ep-001",
        name: "Churn Prediction",
        urlPath: "/v1/models/cust-intl/predict",
        description: "Predict customer churn probability",
        createdAt: new Date("2024-01-16"),
        status: "active",
      },
    ],
  },
  {
    id: "model-002",
    name: "Financial Risk Model",
    description: "AI model for credit risk assessment and fraud detection",
    datasets: [
      {
        datasetId: "ds-002",
        datasetName: "Loan Default Prediction",
        source: "supabase",
        rows: 32581,
        columns: 35,
        connectedAt: new Date("2024-01-14"),
        lastSynced: new Date("2024-01-17"),
        syncStatus: "synced",
      },
      {
        datasetId: "ds-007",
        datasetName: "Fraud Detection",
        source: "supabase",
        rows: 284807,
        columns: 31,
        connectedAt: new Date("2024-01-14"),
        lastSynced: new Date("2024-01-16"),
        syncStatus: "outdated",
      },
    ],
    syncMode: "real-time",
    baseModel: "schema-v0",
    accuracy: 0.891,
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-17"),
    status: "needs-update",
    modelId: "mdl_fin_risk_3m8p1",
    apiRequests: 8432,
    tokensUsed: 1823456,
    trainingMetricsHistory: [
      { epoch: 1, loss: 0.79, accuracy: 0.52 },
      { epoch: 5, loss: 0.55, accuracy: 0.68 },
      { epoch: 10, loss: 0.38, accuracy: 0.78 },
      { epoch: 15, loss: 0.25, accuracy: 0.85 },
      { epoch: 20, loss: 0.18, accuracy: 0.89 },
    ],
    pendingUpdates: [
      {
        datasetId: "ds-007",
        datasetName: "Fraud Detection",
        updateType: "modified",
        detectedAt: new Date("2024-01-18"),
        message: "Source data has been updated with 1,250 new records",
      },
    ],
  },
]

export const generateTrainingProgress = (epoch: number, totalEpochs: number) => {
  const progress = epoch / totalEpochs
  const baseLoss = 0.8 * Math.exp(-3 * progress) + 0.1 + Math.random() * 0.05
  const baseAccuracy = 0.5 + 0.4 * (1 - Math.exp(-4 * progress)) + Math.random() * 0.02

  return {
    epoch,
    totalEpochs,
    loss: Math.max(0.1, baseLoss),
    accuracy: Math.min(0.95, baseAccuracy),
    learningRate: 0.001 * Math.pow(0.95, epoch),
  }
}
