FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl openjdk-17-jdk-headless \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

RUN pip install --no-cache-dir \
    pyspark==3.5.0 \
    flask==3.0.0 \
    pandas==2.1.0 \
    pymongo==4.6.0 \
    psycopg2-binary==2.9.9 \
    pymysql==1.1.0 \
    snowflake-connector-python==3.6.0 \
    google-cloud-storage==2.13.0 \
    boto3==1.34.0

COPY services/spark_app/ /app/

EXPOSE 5000

CMD ["python", "app.py"]
