import type { Dataset, Model } from "./types"

export const mockDatasets: Dataset[] = [
  {
    id: "ds-001",
    name: "Customer Churn Analysis",
    description: "Telecom customer data for predicting churn behavior",
    source: "databricks",
    vertical: "marketing",
    complexity: "medium",
    rowCount: "medium",
    rows: 7043,
    columns: 21,
    lastUpdated: new Date("2024-01-18"),
    syncStatus: "synced",
    schema: [
      { name: "customer_id", type: "string", description: "Unique customer identifier" },
      { name: "tenure", type: "number", description: "Months with company" },
      { name: "monthly_charges", type: "number", description: "Monthly bill amount" },
      { name: "total_charges", type: "number", description: "Total amount charged" },
      { name: "churn", type: "boolean", description: "Whether customer churned" },
    ],
    sampleData: [
      { customer_id: "7590-VHVEG", tenure: 1, monthly_charges: 29.85, total_charges: 29.85, churn: false },
      { customer_id: "5575-GNVDE", tenure: 34, monthly_charges: 56.95, total_charges: 1889.5, churn: false },
    ],
  },
  {
    id: "ds-002",
    name: "Loan Default Prediction",
    description: "Banking data for credit risk assessment",
    source: "supabase",
    vertical: "finance",
    complexity: "advanced",
    rowCount: "large",
    rows: 32581,
    columns: 35,
    lastUpdated: new Date("2024-01-17"),
    syncStatus: "synced",
    schema: [
      { name: "loan_id", type: "string", description: "Unique loan identifier" },
      { name: "loan_amount", type: "number", description: "Principal amount" },
      { name: "interest_rate", type: "number", description: "Annual interest rate" },
      { name: "credit_score", type: "number", description: "Borrower credit score" },
      { name: "default", type: "boolean", description: "Whether loan defaulted" },
    ],
    sampleData: [
      { loan_id: "LN-001", loan_amount: 15000, interest_rate: 7.5, credit_score: 720, default: false },
      { loan_id: "LN-002", loan_amount: 8000, interest_rate: 12.3, credit_score: 645, default: true },
    ],
  },
  {
    id: "ds-003",
    name: "Patient Readmission",
    description: "Hospital records for predicting 30-day readmissions",
    source: "api",
    vertical: "healthcare",
    complexity: "advanced",
    rowCount: "large",
    rows: 25000,
    columns: 42,
    lastUpdated: new Date("2024-01-16"),
    syncStatus: "outdated",
    schema: [
      { name: "patient_id", type: "string", description: "Anonymized patient ID" },
      { name: "age", type: "number", description: "Patient age" },
      { name: "diagnosis_code", type: "string", description: "Primary diagnosis" },
      { name: "length_of_stay", type: "number", description: "Days in hospital" },
      { name: "readmitted", type: "boolean", description: "Readmitted within 30 days" },
    ],
    sampleData: [
      { patient_id: "P-8821", age: 67, diagnosis_code: "I50", length_of_stay: 5, readmitted: true },
      { patient_id: "P-9932", age: 45, diagnosis_code: "J18", length_of_stay: 3, readmitted: false },
    ],
  },
  {
    id: "ds-004",
    name: "E-commerce Transactions",
    description: "Online retail purchase data for demand forecasting",
    source: "google-drive",
    vertical: "e-commerce",
    complexity: "medium",
    rowCount: "medium",
    rows: 8950,
    columns: 18,
    lastUpdated: new Date("2024-01-15"),
    syncStatus: "synced",
    schema: [
      { name: "transaction_id", type: "string", description: "Transaction identifier" },
      { name: "product_category", type: "string", description: "Product category" },
      { name: "quantity", type: "number", description: "Items purchased" },
      { name: "revenue", type: "number", description: "Transaction revenue" },
      { name: "returned", type: "boolean", description: "Item returned" },
    ],
    sampleData: [
      { transaction_id: "TXN-4421", product_category: "Electronics", quantity: 2, revenue: 459.99, returned: false },
      { transaction_id: "TXN-4422", product_category: "Apparel", quantity: 1, revenue: 79.95, returned: true },
    ],
  },
  {
    id: "ds-005",
    name: "Employee Attrition",
    description: "HR analytics data for workforce planning",
    source: "databricks",
    vertical: "hr",
    complexity: "simple",
    rowCount: "small",
    rows: 1470,
    columns: 9,
    lastUpdated: new Date("2024-01-14"),
    syncStatus: "synced",
    schema: [
      { name: "employee_id", type: "string", description: "Employee identifier" },
      { name: "department", type: "string", description: "Department name" },
      { name: "years_at_company", type: "number", description: "Tenure in years" },
      { name: "satisfaction_score", type: "number", description: "Job satisfaction (1-5)" },
      { name: "attrition", type: "boolean", description: "Left the company" },
    ],
    sampleData: [
      { employee_id: "EMP-101", department: "Sales", years_at_company: 3, satisfaction_score: 4, attrition: false },
      {
        employee_id: "EMP-102",
        department: "Engineering",
        years_at_company: 1,
        satisfaction_score: 2,
        attrition: true,
      },
    ],
  },
  {
    id: "ds-006",
    name: "Supply Chain Delays",
    description: "Logistics data for delivery time prediction",
    source: "api",
    vertical: "operations",
    complexity: "medium",
    rowCount: "large",
    rows: 15420,
    columns: 24,
    lastUpdated: new Date("2024-01-13"),
    syncStatus: "pending",
    schema: [
      { name: "shipment_id", type: "string", description: "Shipment tracking ID" },
      { name: "origin", type: "string", description: "Origin warehouse" },
      { name: "destination", type: "string", description: "Delivery destination" },
      { name: "weight_kg", type: "number", description: "Package weight" },
      { name: "delayed", type: "boolean", description: "Shipment was delayed" },
    ],
    sampleData: [
      { shipment_id: "SHP-7721", origin: "NYC", destination: "LAX", weight_kg: 12.5, delayed: false },
      { shipment_id: "SHP-7722", origin: "CHI", destination: "MIA", weight_kg: 8.3, delayed: true },
    ],
  },
  {
    id: "ds-007",
    name: "Fraud Detection",
    description: "Financial transaction data for anomaly detection",
    source: "supabase",
    vertical: "finance",
    complexity: "advanced",
    rowCount: "large",
    rows: 284807,
    columns: 31,
    lastUpdated: new Date("2024-01-12"),
    syncStatus: "synced",
    schema: [
      { name: "transaction_id", type: "string", description: "Unique transaction ID" },
      { name: "amount", type: "number", description: "Transaction amount" },
      { name: "merchant_category", type: "string", description: "Merchant type" },
      { name: "time_delta", type: "number", description: "Time since last transaction" },
      { name: "is_fraud", type: "boolean", description: "Fraudulent transaction" },
    ],
    sampleData: [
      { transaction_id: "FT-001", amount: 149.62, merchant_category: "retail", time_delta: 0, is_fraud: false },
      { transaction_id: "FT-002", amount: 2.69, merchant_category: "online", time_delta: 0.5, is_fraud: false },
    ],
  },
  {
    id: "ds-008",
    name: "Marketing Campaign Response",
    description: "Direct marketing data for conversion prediction",
    source: "google-drive",
    vertical: "marketing",
    complexity: "simple",
    rowCount: "medium",
    rows: 4521,
    columns: 12,
    lastUpdated: new Date("2024-01-11"),
    syncStatus: "synced",
    schema: [
      { name: "contact_id", type: "string", description: "Contact identifier" },
      { name: "age", type: "number", description: "Customer age" },
      { name: "income", type: "number", description: "Annual income" },
      { name: "campaign_type", type: "string", description: "Campaign channel" },
      { name: "converted", type: "boolean", description: "Made a purchase" },
    ],
    sampleData: [
      { contact_id: "C-881", age: 35, income: 72000, campaign_type: "email", converted: true },
      { contact_id: "C-882", age: 28, income: 45000, campaign_type: "social", converted: false },
    ],
  },
  // Databricks - Product Alpha Financials
  {
    id: "ds-009",
    name: "Product Alpha Financials",
    description: "Financial performance data for Product Alpha including revenue, costs, and profitability metrics",
    source: "databricks",
    vertical: "finance",
    complexity: "advanced",
    rowCount: "large",
    rows: 48520,
    columns: 28,
    lastUpdated: new Date("2024-01-19"),
    syncStatus: "synced",
    schema: [
      { name: "record_id", type: "string", description: "Unique record identifier" },
      { name: "date", type: "date", description: "Transaction date" },
      { name: "revenue", type: "number", description: "Daily revenue in USD" },
      { name: "cogs", type: "number", description: "Cost of goods sold" },
      { name: "gross_margin", type: "number", description: "Gross margin percentage" },
      { name: "operating_expenses", type: "number", description: "Operating expenses" },
      { name: "net_profit", type: "number", description: "Net profit" },
      { name: "units_sold", type: "number", description: "Number of units sold" },
      { name: "region", type: "string", description: "Sales region" },
      { name: "channel", type: "string", description: "Sales channel" },
    ],
    sampleData: [
      { record_id: "PA-001", date: "2024-01-15", revenue: 125000, cogs: 45000, gross_margin: 64, operating_expenses: 32000, net_profit: 48000, units_sold: 1250, region: "North America", channel: "Direct" },
      { record_id: "PA-002", date: "2024-01-15", revenue: 89000, cogs: 31000, gross_margin: 65.2, operating_expenses: 24000, net_profit: 34000, units_sold: 890, region: "Europe", channel: "Partner" },
    ],
  },
  // Databricks - Product Beta Financials
  {
    id: "ds-010",
    name: "Product Beta Financials",
    description: "Financial performance data for Product Beta including revenue streams and market analysis",
    source: "databricks",
    vertical: "finance",
    complexity: "advanced",
    rowCount: "large",
    rows: 36840,
    columns: 32,
    lastUpdated: new Date("2024-01-19"),
    syncStatus: "synced",
    schema: [
      { name: "record_id", type: "string", description: "Unique record identifier" },
      { name: "date", type: "date", description: "Transaction date" },
      { name: "revenue", type: "number", description: "Daily revenue in USD" },
      { name: "subscription_revenue", type: "number", description: "Recurring subscription revenue" },
      { name: "one_time_revenue", type: "number", description: "One-time purchase revenue" },
      { name: "customer_acquisition_cost", type: "number", description: "CAC per customer" },
      { name: "lifetime_value", type: "number", description: "Customer LTV" },
      { name: "churn_rate", type: "number", description: "Monthly churn rate" },
      { name: "active_subscribers", type: "number", description: "Active subscriber count" },
      { name: "market_segment", type: "string", description: "Target market segment" },
    ],
    sampleData: [
      { record_id: "PB-001", date: "2024-01-15", revenue: 78000, subscription_revenue: 65000, one_time_revenue: 13000, customer_acquisition_cost: 245, lifetime_value: 2400, churn_rate: 2.3, active_subscribers: 4520, market_segment: "Enterprise" },
      { record_id: "PB-002", date: "2024-01-15", revenue: 45000, subscription_revenue: 38000, one_time_revenue: 7000, customer_acquisition_cost: 125, lifetime_value: 890, churn_rate: 4.1, active_subscribers: 12800, market_segment: "SMB" },
    ],
  },
  // API - NBA Statistics
  {
    id: "ds-011",
    name: "NBA Player Statistics",
    description: "Comprehensive NBA player and team statistics from the official NBA API",
    source: "api",
    vertical: "sports",
    complexity: "medium",
    rowCount: "large",
    rows: 15420,
    columns: 45,
    lastUpdated: new Date("2024-01-19"),
    syncStatus: "synced",
    schema: [
      { name: "player_id", type: "string", description: "Unique player identifier" },
      { name: "player_name", type: "string", description: "Player full name" },
      { name: "team", type: "string", description: "Current team" },
      { name: "position", type: "string", description: "Playing position" },
      { name: "games_played", type: "number", description: "Games played this season" },
      { name: "points_per_game", type: "number", description: "Average points per game" },
      { name: "rebounds_per_game", type: "number", description: "Average rebounds per game" },
      { name: "assists_per_game", type: "number", description: "Average assists per game" },
      { name: "field_goal_pct", type: "number", description: "Field goal percentage" },
      { name: "three_point_pct", type: "number", description: "Three-point percentage" },
    ],
    sampleData: [
      { player_id: "NBA-001", player_name: "LeBron James", team: "Los Angeles Lakers", position: "SF", games_played: 45, points_per_game: 25.4, rebounds_per_game: 7.2, assists_per_game: 8.1, field_goal_pct: 54.2, three_point_pct: 38.5 },
      { player_id: "NBA-002", player_name: "Stephen Curry", team: "Golden State Warriors", position: "PG", games_played: 42, points_per_game: 29.8, rebounds_per_game: 4.5, assists_per_game: 5.2, field_goal_pct: 48.1, three_point_pct: 42.8 },
    ],
  },
  // API - Serie A Statistics
  {
    id: "ds-012",
    name: "Serie A League Statistics",
    description: "Italian Serie A football league statistics including player and team performance data",
    source: "api",
    vertical: "sports",
    complexity: "medium",
    rowCount: "large",
    rows: 12850,
    columns: 38,
    lastUpdated: new Date("2024-01-19"),
    syncStatus: "synced",
    schema: [
      { name: "player_id", type: "string", description: "Unique player identifier" },
      { name: "player_name", type: "string", description: "Player full name" },
      { name: "club", type: "string", description: "Current club" },
      { name: "nationality", type: "string", description: "Player nationality" },
      { name: "position", type: "string", description: "Playing position" },
      { name: "appearances", type: "number", description: "League appearances" },
      { name: "goals", type: "number", description: "Goals scored" },
      { name: "assists", type: "number", description: "Assists provided" },
      { name: "minutes_played", type: "number", description: "Total minutes played" },
      { name: "pass_accuracy", type: "number", description: "Pass accuracy percentage" },
    ],
    sampleData: [
      { player_id: "SA-001", player_name: "Lautaro Martinez", club: "Inter Milan", nationality: "Argentina", position: "ST", appearances: 22, goals: 15, assists: 4, minutes_played: 1890, pass_accuracy: 82.3 },
      { player_id: "SA-002", player_name: "Victor Osimhen", club: "Napoli", nationality: "Nigeria", position: "ST", appearances: 18, goals: 12, assists: 3, minutes_played: 1520, pass_accuracy: 76.8 },
    ],
  },
  // Supabase - F1 Statistics
  {
    id: "ds-013",
    name: "F1 Racing Analytics",
    description: "Formula 1 racing data including driver performance, lap times, and race results",
    source: "supabase",
    vertical: "sports",
    complexity: "advanced",
    rowCount: "large",
    rows: 28450,
    columns: 52,
    lastUpdated: new Date("2024-01-19"),
    syncStatus: "synced",
    schema: [
      { name: "race_id", type: "string", description: "Unique race identifier" },
      { name: "driver_id", type: "string", description: "Driver identifier" },
      { name: "driver_name", type: "string", description: "Driver full name" },
      { name: "team", type: "string", description: "Constructor team" },
      { name: "grand_prix", type: "string", description: "Grand Prix name" },
      { name: "position", type: "number", description: "Final race position" },
      { name: "points", type: "number", description: "Points earned" },
      { name: "fastest_lap", type: "string", description: "Fastest lap time" },
      { name: "avg_speed_kmh", type: "number", description: "Average speed in km/h" },
      { name: "pit_stops", type: "number", description: "Number of pit stops" },
    ],
    sampleData: [
      { race_id: "F1-2024-01", driver_id: "VER", driver_name: "Max Verstappen", team: "Red Bull Racing", grand_prix: "Bahrain GP", position: 1, points: 25, fastest_lap: "1:32.608", avg_speed_kmh: 215.4, pit_stops: 2 },
      { race_id: "F1-2024-01", driver_id: "HAM", driver_name: "Lewis Hamilton", team: "Mercedes", grand_prix: "Bahrain GP", position: 3, points: 15, fastest_lap: "1:33.124", avg_speed_kmh: 214.8, pit_stops: 2 },
    ],
  },
]

export const mockModels: Model[] = [
  {
    id: "model-001",
    name: "Customer Intelligence",
    description: "AI model for customer behavior analysis and churn prediction",
    datasets: [
      {
        datasetId: "ds-001",
        datasetName: "Customer Churn Analysis",
        source: "databricks",
        rows: 7043,
        columns: 21,
        connectedAt: new Date("2024-01-15"),
        lastSynced: new Date("2024-01-18"),
        syncStatus: "synced",
      },
      {
        datasetId: "ds-008",
        datasetName: "Marketing Campaign Response",
        source: "google-drive",
        rows: 4521,
        columns: 12,
        connectedAt: new Date("2024-01-15"),
        lastSynced: new Date("2024-01-17"),
        syncStatus: "synced",
      },
    ],
    syncMode: "real-time",
    baseModel: "schema-v0",
    accuracy: 0.923,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-18"),
    status: "completed",
    modelId: "mdl_cust_intl_7x9k2",
    apiRequests: 12847,
    tokensUsed: 2456890,
    trainingMetricsHistory: [
      { epoch: 1, loss: 0.82, accuracy: 0.54 },
      { epoch: 5, loss: 0.58, accuracy: 0.71 },
      { epoch: 10, loss: 0.34, accuracy: 0.82 },
      { epoch: 15, loss: 0.21, accuracy: 0.89 },
      { epoch: 20, loss: 0.14, accuracy: 0.92 },
    ],
    endpoints: [
      {
        id: "ep-001",
        name: "Churn Prediction",
        urlPath: "/v1/models/cust-intl/predict",
        description: "Predict customer churn probability",
        createdAt: new Date("2024-01-16"),
        status: "active",
      },
    ],
  },
  {
    id: "model-002",
    name: "Financial Risk Model",
    description: "AI model for credit risk assessment and fraud detection",
    datasets: [
      {
        datasetId: "ds-002",
        datasetName: "Loan Default Prediction",
        source: "supabase",
        rows: 32581,
        columns: 35,
        connectedAt: new Date("2024-01-14"),
        lastSynced: new Date("2024-01-17"),
        syncStatus: "synced",
      },
      {
        datasetId: "ds-007",
        datasetName: "Fraud Detection",
        source: "supabase",
        rows: 284807,
        columns: 31,
        connectedAt: new Date("2024-01-14"),
        lastSynced: new Date("2024-01-16"),
        syncStatus: "outdated",
      },
    ],
    syncMode: "real-time",
    baseModel: "schema-v0",
    accuracy: 0.891,
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-17"),
    status: "needs-update",
    modelId: "mdl_fin_risk_3m8p1",
    apiRequests: 8432,
    tokensUsed: 1823456,
    trainingMetricsHistory: [
      { epoch: 1, loss: 0.79, accuracy: 0.52 },
      { epoch: 5, loss: 0.55, accuracy: 0.68 },
      { epoch: 10, loss: 0.38, accuracy: 0.78 },
      { epoch: 15, loss: 0.25, accuracy: 0.85 },
      { epoch: 20, loss: 0.18, accuracy: 0.89 },
    ],
    pendingUpdates: [
      {
        datasetId: "ds-007",
        datasetName: "Fraud Detection",
        updateType: "modified",
        detectedAt: new Date("2024-01-18"),
        message: "Source data has been updated with 1,250 new records",
      },
    ],
  },
  // Product Alpha Financial Model
  {
    id: "model-003",
    name: "Product Alpha Analytics",
    description: "AI model for Product Alpha financial analysis, revenue forecasting, and profitability insights",
    datasets: [
      {
        datasetId: "ds-009",
        datasetName: "Product Alpha Financials",
        source: "databricks",
        rows: 48520,
        columns: 28,
        connectedAt: new Date("2024-01-17"),
        lastSynced: new Date("2024-01-19"),
        syncStatus: "synced",
      },
    ],
    syncMode: "real-time",
    baseModel: "schema-v0",
    accuracy: 0.945,
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-19"),
    status: "completed",
    modelId: "mdl_prod_alpha_9k2x",
    apiRequests: 5621,
    tokensUsed: 1245780,
    trainingMetricsHistory: [
      { epoch: 1, loss: 0.75, accuracy: 0.58 },
      { epoch: 5, loss: 0.48, accuracy: 0.74 },
      { epoch: 10, loss: 0.28, accuracy: 0.86 },
      { epoch: 15, loss: 0.16, accuracy: 0.92 },
      { epoch: 20, loss: 0.09, accuracy: 0.945 },
    ],
    endpoints: [],
  },
  // Product Beta Financial Model
  {
    id: "model-004",
    name: "Product Beta Analytics",
    description: "AI model for Product Beta subscription analytics, churn prediction, and LTV optimization",
    datasets: [
      {
        datasetId: "ds-010",
        datasetName: "Product Beta Financials",
        source: "databricks",
        rows: 36840,
        columns: 32,
        connectedAt: new Date("2024-01-17"),
        lastSynced: new Date("2024-01-19"),
        syncStatus: "synced",
      },
    ],
    syncMode: "real-time",
    baseModel: "schema-v0",
    accuracy: 0.932,
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-19"),
    status: "completed",
    modelId: "mdl_prod_beta_4m7p",
    apiRequests: 4892,
    tokensUsed: 987450,
    trainingMetricsHistory: [
      { epoch: 1, loss: 0.78, accuracy: 0.55 },
      { epoch: 5, loss: 0.52, accuracy: 0.72 },
      { epoch: 10, loss: 0.32, accuracy: 0.84 },
      { epoch: 15, loss: 0.19, accuracy: 0.90 },
      { epoch: 20, loss: 0.12, accuracy: 0.932 },
    ],
    endpoints: [],
  },
]

export const generateTrainingProgress = (epoch: number, totalEpochs: number) => {
  const progress = epoch / totalEpochs
  const baseLoss = 0.8 * Math.exp(-3 * progress) + 0.1 + Math.random() * 0.05
  const baseAccuracy = 0.5 + 0.4 * (1 - Math.exp(-4 * progress)) + Math.random() * 0.02

  return {
    epoch,
    totalEpochs,
    loss: Math.max(0.1, baseLoss),
    accuracy: Math.min(0.95, baseAccuracy),
    learningRate: 0.001 * Math.pow(0.95, epoch),
  }
}
